#cloud-config
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    plain_text_passwd: ubuntu
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}
  - name: dev
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    plain_text_passwd: dev123
    lock_passwd: false
    ssh_authorized_keys:
      - ${ssh_public_key}    

# Enable SSH
ssh_pwauth: true
disable_root: true

# Package updates
package_update: true
package_upgrade: false

# Install basic packages
packages:
  - curl
  - wget
  - vim
  - htop

# Set hostname
hostname: ${hostname}

# Final message
final_message: "Cloud-init setup complete. System ready."